# Generated by Django 2.0.3 on 2018-03-10 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_four', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ended_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(2)]),
        ),
    ]
